// Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace ArifTestApi.Models
{
    // Represents the Employee table structure
    public class Employee
    {
        // EmployeeID is typically auto-generated by the database, so it's not required for POST requests.
        // It's included here for completeness if you were to fetch data.
        public int EmployeeID { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public string? Designation { get; set; }
        public string? Post { get; set; }
        public string? ContactNo { get; set; }
        public string? District { get; set; }
        public string? PresentAddress { get; set; }
        public string? PermanentAddress { get; set; }
        public string? EducationQualification { get; set; }
        public string? Remarks { get; set; }
    }
}